---
- name: Change port number
  hosts: all
  gather_facts: no
  tasks:
    - name: Change /etc/ssh/sshd_config
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port 2222"