---
- name:
  hosts: web1
  gather_facts: no
  tasks:
    - name: Ping hosts
      ping:
    - name: Ensure SELinux is set to enforcing mode
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=disabled
    - name: Restart server
      reboot:
        msg: "Server is restarted"
    - name: Wait
      pause:
        minutes: 5
    - name: Setup alternate SSH port
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^#Port 22"
        line: "Port 1677"
    - name: Restart server
      reboot:
        msg: "Server is restarted"
    - name: Wait
      pause:
        minutes: 5
    - name: Restart sshd
      systemd:
        name: sshd
        state: restarted