---
- name: Conditional 1 Playbook
  hosts: web2
  gather_facts: no
  tasks:
    - name: Setup alternate SSH port
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^Port 2222"
        line: "Port 7789"
    - name: Restart sshd
      systemd:
        name: sshd
        state: restarted